### ISSUE TITLE
Reproducable Crash (Incompatibilty Issues) 

### ISSUE THREAD

**Issue by Xionet** [Sunconure11/WearableBackpacks#8]
(Using Modrinth App)
MC 1.19.2 + Fabric 0.14.22

Create (0.5.1.c) + Sodium (0.4.4) + Wearable Backpacks (4.0.0)

Additional dependencies present: 
Fabric API 0.76.1
Cloth Config API 8.3.103

**Comment by Sunconure11** [comment]
It's Sodium. I'm trying to find a solution, but the other guy who has been helping me is busy.

@danikingrd

**Comment by Xionet** [comment]
Ahhhh alright, no worries. Thanks for looking into it either way tho and hopefully it will be an easy fix.

**Comment by Answordy** [comment]
Any update on this issue? Im looking forward to use this mod so much, as its the best one out there imo, being vanilla but also wearable with a nice 3d design.

**Comment by Sunconure11** [comment]
@DanikingRD and @mysticpasta1 were working on aiding me with a fix, but the former is fairly busy.

**Comment by Sunconure11** [comment]
I've pushed out a new build. See if it works.

**Comment by ldanidev** [comment]
I will be working on this from now on in case its still crashing

> I've pushed out a new build. See if it works.

**Comment by Sunconure11** [comment]
@DanikingRD Check Discord
